'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Clock3, MapPin, Plus, Radio, ShieldAlert } from 'lucide-react';
import { useApp } from '../app-provider';
import { useChat } from '../chat/chat-context';
import { Badge, clock, duration, Empty, readableStatus, Severity } from '../ui';
import { NewIncident } from '../incidents/new-incident';
import { zones } from '@/lib/seed';
export function CommandCenter() {
  const { state } = useApp(); const chat = useChat(); const [create, setCreate] = useState(false), [zone, setZone] = useState('');
  if (!state) return null;
  const active = state.incidents.filter(i => !['RESOLVED', 'ARCHIVED'].includes(i.status)), resolved = state.incidents.filter(i => i.report);
  const visible = zone ? active.filter(i => i.zone === zone) : active;
  const avg = resolved.length ? duration(resolved.reduce((n, i) => n + i.report!.durationSeconds, 0) / resolved.length) : '—';
  const online = state.staff.filter(s => chat.presence[s.uid] === 'online').length;
  return <><div className="page-heading"><div><div className="eyebrow">NOVAHACK 2026 <span className="subtle">/ OPERATIONS</span></div><h1>Command center<span className="live-tag"><span className="connection-dot on" /> EVENT OPEN</span></h1><p>The whole event, in view. Keep the response moving.</p></div><button className="button" onClick={() => setCreate(true)}><Plus size={16} /> Report incident</button></div>
    <div className="metrics"><div><span>Event health</span><strong className={active.some(i => i.severity === 'P1') ? 'text-red' : active.length ? 'text-amber' : 'text-green'}>{active.some(i => i.severity === 'P1') ? 'Critical' : active.length ? 'Needs attention' : 'Steady'}</strong><small>{active.length ? `${active.length} area${active.length > 1 ? 's' : ''} require a response` : 'No active incident reports'}</small></div><div><span>Active incidents</span><strong>{String(active.length).padStart(2, '0')}<ShieldAlert size={18} /></strong><small>{resolved.length} resolved this session</small></div><div><span>Staff online</span><strong>{chat.status === 'ready' ? `${online} / ${state.staff.length}` : '—'}<Radio size={18} /></strong><small>{chat.status === 'ready' ? 'Live CometChat presence' : 'Connect chat for live presence'}</small></div><div><span>Avg. resolution</span><strong>{avg}<Clock3 size={18} /></strong><small>{resolved.length ? `Across ${resolved.length} resolved incidents` : 'Measured after the first resolution'}</small></div></div>
    <div className="command-grid"><section className="panel venue-panel"><div className="panel-heading"><h2>Venue pulse</h2><span className="muted mono">8 ZONES</span></div><div className="venue-legend"><span><i className="dot green" /> No reported incident</span><span><i className="dot amber" /> Needs attention</span><span><i className="dot red" /> Critical</span></div><div className="venue-map">{zones.map((z, index) => { const items = active.filter(i => i.zone === z); const tone = items.some(i => i.severity === 'P1') ? 'red' : items.length ? 'amber' : 'green'; return <button key={z} className={`map-zone zone-${index} ${items.length ? tone : ''} ${zone === z ? 'selected' : ''}`} onClick={() => setZone(zone === z ? '' : z)}><span className="zone-meta"><span className="mono">{String(index + 1).padStart(2, '0')}</span><i className={`dot ${tone}`} /></span><strong>{z}</strong><small>{items.length ? `${items.length} active incident` : 'No reported incident'}</small>{items.length > 0 && <ArrowUpRight size={16} />}</button>; })}<div className="map-corridor"><span className="mono">MAIN CONCOURSE</span><span className="map-dashes" /></div></div><div className="panel-foot"><span><MapPin size={13} /> Venue schematic · not to scale</span><button className="text-button" onClick={() => setZone('')}>{zone ? 'Clear zone filter' : 'All zones in view'}</button></div></section>
    <section className="panel feed-panel"><div className="panel-heading"><h2>Live activity</h2><Badge tone="neutral">SESSION FEED</Badge></div><div className="activity-feed">{state.feed.slice(0, 7).map(item => <div className="feed-item" key={item.id}><span className={`feed-marker ${item.kind}`} /> <div><p>{item.text}</p><small className="mono">{clock(item.at)} IST <span>· {item.kind}</span></small></div></div>)}</div><Link href="/simulation" className="feed-cta">Run a scenario <ArrowRight size={15} /></Link></section>
    <section className="panel incident-panel"><div className="panel-heading"><h2>Active incidents {zone && <span className="muted">/ {zone}</span>}</h2><Link href="/incidents">View all <ArrowUpRight size={14} /></Link></div>{visible.length ? <div className="incident-rows">{visible.map(i => <Link href={`/incidents/${i.id}`} key={i.id} className="incident-row"><span className="incident-icon"><ShieldAlert size={19} /></span><div className="incident-name"><span className="mono muted">{i.id}</span><strong>{i.title}</strong><small>{i.zone} · {i.relatedMessageIds.length} linked reports</small></div><Severity value={i.severity} /><Badge>{readableStatus(i.status)}</Badge><span className="mono muted">{clock(i.createdAt)}</span><ChevronRight size={16} /></Link>)}</div> : <Empty title={zone ? 'No active incidents in this zone' : 'A clear desk. Keep listening.'} action={<Link href="/simulation" className="button">Try the registration scenario <ArrowRight size={15} /></Link>}>Reports from your team channels appear here when related signals point to a problem.</Empty>}</section></div>
    <div className="desk-note"><Check size={15} /><span>Observed reports and inferred explanations stay separate. Every assignment requires a human decision.</span><span className="mono">EVENTOPS / COMMAND</span></div>{create && <NewIncident onClose={() => setCreate(false)} />}</>;
}
