'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Radio, MapPin, Users, ShieldCheck, MessageSquare } from 'lucide-react';
import { useApp } from '@/components/app-provider';
import { staff } from '@/lib/seed';
import { Avatar, Badge } from '@/components/ui';
export default function Home() {
  const { state, request, busy } = useApp(); const router = useRouter(); const [uid, setUid] = useState('eventops-maya'), [accessCode, setAccessCode] = useState('');
  return <div className="landing"><header className="landing-nav"><Link className="brand" href="/"><span className="brand-mark"><Radio size={21} /></span>eventops<span className="brand-period">.</span></Link><span className="mono">LIVE EVENT OPERATIONS</span><a href="https://github.com/1shu1iwari-crypto/Event-Chat" target="_blank" rel="noreferrer">View project <ArrowUpRight size={15} /></a></header><main className="landing-main"><section className="landing-copy"><span className="eyebrow"><span className="connection-dot on" /> THE OPERATIONS DESK IS OPEN</span><h1>Every signal.<br />One coordinated<br /><span>response.</span></h1><p>From group chats to coordinated operations. Bring your people, conversations, and live incidents into one shared command center.</p><div className="landing-principles"><span><MessageSquare size={17} /> Real communication</span><span><ShieldCheck size={17} /> Human decisions</span></div><div className="landing-footnote"><span className="mono">BUILT FOR THE MOMENT</span><p>After the doors open. When the queue grows.<br />When someone needs to make the call.</p></div></section><section className="event-entry"><div className="event-poster"><span className="mono">NOVA / 2026</span><div className="poster-orbit"><span>N</span></div><div><Badge tone="green">DEMO EVENT</Badge><h2>NovaHack 2026</h2><p>One thousand builders. One operations desk.</p></div></div><div className="entry-body"><div className="event-meta"><span><MapPin size={15} /> 8 venue zones</span><span><Users size={15} /> 8 demo responders</span></div>{state?.viewer ? <><div className="signed-in"><Avatar name={state.viewer.name} small /><span>Signed in as <strong>{state.viewer.name}</strong></span></div><Link href="/command" className="button primary full">Enter command center <ArrowRight size={17} /></Link><button className="text-button full" onClick={() => void request('logout').catch(() => {})}>Switch demo persona</button></> : <form onSubmit={e => { e.preventDefault(); void request('session', { uid, accessCode }).then(() => router.push('/command')).catch(() => {}); }}><label>Choose your demo role<select value={uid} onChange={e => setUid(e.target.value)}>{staff.map(s => <option value={s.uid} key={s.uid}>{s.name} · {s.role}</option>)}</select></label><label>Event access code<input type="password" autoComplete="current-password" placeholder="Required on shared deployments" value={accessCode} onChange={e => setAccessCode(e.target.value)} /></label><button className="button primary full" disabled={busy}>{busy ? 'Opening workspace…' : 'Enter command center'}<ArrowRight size={17} /></button><p className="entry-note">Demo identities are fictional. Access code is optional on localhost.</p></form>}</div></section></main><footer className="landing-footer"><span>EventOps / CometChat Zero to Chat</span><span>People stay in command.</span></footer></div>;
}
